services:
  lamports-factory:
    image: lamports-factory:local
    container_name: lamports-factory
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
    environment:
      BASE_URL: /
      STATIC_DIR: /src/server/public
      TEX_DIR: /app/workspace
      BUILD_DIR_NAME: build
      TEX_MAIN: sample/main.tex
      # latex engine examples: lualatex | xelatex | pdflatex | platex | uplatex
      LATEX_ENGINE: lualatex
      # Override latexmk options directly when needed.
      # LATEXMK_OPTS: "-lualatex -interaction=nonstopmode"
      # reload mode examples: sse | poll | ws
      RELOAD_MODE: sse
      # layout mode examples: preview | split
      # If TTYD_ENABLED is disable, split falls back to preview.
      LAYOUT_MODE: preview # split
      NVIM_CONFIG_REPO: "https://github.com/recelsus/nvim.git"
      # bootstrap examples: enable | disable
      NVIM_BOOTSTRAP_ON_INIT: enable
      # ttyd examples: enable | disable
      TTYD_ENABLED: enable
    volumes:
      - ..:/src
      - ./workspace:/app/workspace
      - ./volumes/texmf:/app/texmf
      - ./volumes/fonts:/app/fonts
      - ./volumes/nvim:/app/nvim
    ports:
      - "8080:8080"
    restart: unless-stopped
