set-option -g prefix None
unbind-key -a

set-option -g default-terminal "tmux-256color"
set-option -ga terminal-features ",xterm-256color:RGB"
set-option -ga terminal-features ",tmux-256color:RGB"
set-option -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY TERM COLORTERM LANG LC_ALL LC_CTYPE"
set-option -g status off
set-option -g mode-keys vi
set-option -g mouse off
set-option -g escape-time 10
set-option -g detach-on-destroy off
set-option -g renumber-windows off
set-option -g set-titles on
set-option -g set-titles-string "LamportsFactory"

set-option -g allow-rename off
set-option -g automatic-rename off
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g display-time 1000

set-window-option -g mode-keys vi
set-window-option -g monitor-activity off
set-window-option -g aggressive-resize on
